const Events = require('../models/event')

// const testEvent =  async(req, res) => {
//     res.json({ message: 'API is working' });
// }

const addNewEvent = async(req, res) => {
    try {
      if (req.body.type === 'service') {
        // For services, check if one already exists for this date
        const serviceDate = new Date(req.body.startDate);
        serviceDate.setHours(0, 0, 0, 0);
        
        const existingService = await Events.findOne({
          type: 'service',
          startDate: {
            $gte: new Date(serviceDate),
            $lt: new Date(serviceDate.getTime() + 24 * 60 * 60 * 1000)
          }
        });

        if (existingService) {
          // Update existing service
          await Events.findByIdAndUpdate(existingService._id, req.body);
          res.json({
            msg: "Service schedule updated successfully",
          });
        } else {
          // Create new service
          const data = await Events.create(req.body);
          if (data) {
            res.json({
              msg: "Service schedule saved successfully",
            });
          }
        }
      } else {
        // For regular events, just create
        const data = await Events.create(req.body);
        if (data) {
          res.json({
            msg: "Event added successfully",
          });
        }
      }
    } catch (error) {
      console.error('Error adding event:', error);
      res.status(500).json({
        msg: "Failed to add event",
        error: error.message
      });
    }
}

const getEvent = async(req, res) => {
    try {
        // Get all saved events and services
        const savedData = await Events.find();
        
        // Generate all Saturdays for the next year
        const saturdays = [];
        const today = new Date();
        const oneYearFromNow = new Date(today);
        oneYearFromNow.setFullYear(today.getFullYear() + 1);
        
        // Find the next Saturday
        const currentDate = new Date(today);
        const dayOfWeek = currentDate.getDay(); // 0 = Sunday, 6 = Saturday
        const daysUntilSaturday = dayOfWeek === 6 ? 0 : (6 - dayOfWeek);
        currentDate.setDate(currentDate.getDate() + daysUntilSaturday);
        
        // Generate all Saturdays
        while (currentDate <= oneYearFromNow) {
            const saturdayDate = new Date(currentDate);
            saturdayDate.setHours(0, 0, 0, 0);
            
            // Check if there's a saved service for this Saturday
            const savedService = savedData.find(item => {
                if (item.type === 'service') {
                    const savedDate = new Date(item.startDate);
                    savedDate.setHours(0, 0, 0, 0);
                    return savedDate.getTime() === saturdayDate.getTime();
                }
                return false;
            });
            
            if (savedService) {
                // Use the saved service with all its details
                saturdays.push(savedService);
            } else {
                // Create a default Saturday Service entry
                saturdays.push({
                    _id: `auto_${saturdayDate.getTime()}`,
                    type: 'service',
                    eventTitle: 'Saturday Service',
                    startDate: saturdayDate,
                    endDate: new Date(saturdayDate),
                    serviceCoordinator: null,
                    choirLead: null,
                    specialPrayers: null,
                    sermonSpeaker: null,
                    offeringsCollectionTeam: null,
                    offeringsCountingTeam: null,
                    isAutoGenerated: true,
                });
            }
            
            // Move to next Saturday
            currentDate.setDate(currentDate.getDate() + 7);
        }
        
        // Get all regular events (type: 'event')
        const regularEvents = savedData.filter(item => item.type === 'event');
        
        // Combine services and events, sort by date
        const allEvents = [...saturdays, ...regularEvents].sort((a, b) => {
            return new Date(a.startDate) - new Date(b.startDate);
        });
        
        res.json(allEvents);
      } catch (error) {
        console.error(error);
        res.status(500).json({ error: 'Internal server error' });
      }

}



module.exports = {addNewEvent, getEvent}